### ISSUE TITLE
CA website documents

### ISSUE THREAD

**Issue by mhf-ir** [alainwolf/roll.urown.net#2]
First of all thank you for greate project.

what's section `auth_info_access` and `crl_dist` and accourding to ca website using nginx how to tell update ca if clients using older version of them?
https://roll.urown.net/ca/ca_root_setup.html
https://roll.urown.net/ca/ca_site.html

Files is `example.net_Root_Certification_Authority.cert.pem` and `example.net_Root_Certification_Authority.crl` when we generate them and what's the name path of orginal files ?

**Comment by alainwolf** [comment]
Sorry but I don't understand your question. Can you rephrase?
