### ISSUE TITLE
git warns collided case-sensitive paths

### ISSUE THREAD

**Issue by schemacs** [alainwolf/roll.urown.net#9]
```
$ git clone https://github.com/alainwolf/roll.urown.net
...
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'server/config-files/etc/mysql/conf.d/BinLog.cnf'
  'server/config-files/etc/mysql/conf.d/binlog.cnf'
  'server/config-files/etc/mysql/conf.d/TLS.cnf'
  'server/config-files/etc/mysql/conf.d/tls.cnf'
```

**Comment by tms320** [comment]
I updated git to v.2.27 (Windows 10 x64). But have the same problem when cloning the repo:
![git_case-sens_bug](https://user-images.githubusercontent.com/24802646/84019214-a742ad80-a989-11ea-9c5b-5ebf7fd52e61.png)
Pay attention to the first two letters of the file name and it's case: "На....ipt" (it is in russian).
When I open the cloned repo, I see that the repo has changes (I use GUI-tool "Git Extensions"):
![git_case-sens_bug2](https://user-images.githubusercontent.com/24802646/84020123-035a0180-a98b-11ea-8bbe-95861ff46c29.png)
But the file isn't deleted. His name only begins with "На..." (not "НА...").
Deleting the file or renaming it to "НАконечник..." doesn't help.
If I press "Stage All" button then the staged changes stay empty i.e. I can't do commit.
